check50:
  files:
    - !exclude "*"
    - !require "create.py"
    - !require "read.py"
    - !require "update.py"
    - !require "delete.py"
    - !require "insert.py"
    - !require "drop.py"
    - !require "pitch.txt"
    - !require "all_students.db"
    - !require "points.csv"

submit50:
  files:
    - !exclude "*"
    - !require "create.py"
    - !require "read.py"
    - !require "update.py"
    - !require "delete.py"
    - !require "insert.py"
    - !require "drop.py"
    - !require "pitch.txt"
    - !require "all_students.db"
    - !require "points.csv"
